# Generated by Django 5.1.3 on 2024-11-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.CharField(max_length=15),
        ),
    ]
